spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://dev-db1.yzkj.net:3306/db_live_old?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
    druid:
      #初始化连接数
      initial-size: 1
      #最小空闲连接数
      min-idle: 10
      #最大连接数
      max-active: 100
      #获取连接等待超时的时间
      max-wait: 60000
      filters: stat,config
      stat-view-servlet:
        #是否开启监控
        enabled: true
        #监控访问路径
        url-pattern: /druid/*
        #允许清空统计数据
        reset-stat-enable: true
        login-username: druid
        login-password: druid
        allow:
  #mq配置
  rabbitmq:
    addresses: dev-mq1.yzkj.net:5672,dev-mq1.yzkj.net:15672,dev-mq1.yzkj.net:25672
    username: rbmq
    password: 123456
  #redis配置
  redis:
    host: dev-redis1.yzkj.net
    port: 6379
    password: 123456
    database: 0
    jedis:
      pool:
        max-active: 800
        max-idle: 20
        min-idle: 2

# 日志配置
logging:
  level:
    com.bh.live: debug
    org.springframework: warn


#jwt的校验设置
cms:
  jwt:
    secret: dfiads@nn*803jk(kjdf)!
    issuer: dewq[!dDDGSaHdf@dUool!1f25+d
    expire-Time: 1800 #30分钟

#无需拦截的请求
excludePathList: "/platUser/login,/platUser/vercode,/platbase/initResource,/platUser/getDynamicKey,/platUser/logout"

#有效时长
platUser:
  expire: 6000

aliyun:
  oss:
    bucketName: live-prd
    endpoint: http://oss-cn-hongkong.aliyuncs.com
    accessKeyId: LTAI1v9Fxyy1qIht
    accessKeySecret: aVFTHSbQLrQPVihWLHy4VGBboOY6rz

#文件上传根目录，按照环境值改 dev/,prd/,tst/,uat
filedir: "dev/"

#阿里云自有域名，上传成功后需要把bucketName改成自有域名
ownName: "http://live-oss.qukanhai.cn"

# 前端用户加密生成token
access:
  jwt:
    token:
      secret: dfiads@nn*803jk(kjdf)!
      issuer: dewq[!dDDGSaHdf@dUool!1f25+d
      expire-Time: 1800 #30分钟
      week-Expire-Time: 604800 #一周

#手动开奖、手动重置开奖
award:
  lottery:
    url: http://192.168.2.201:9310/award/lottery